/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.User;
import ticket.booking.menu.UserMenu;
import ticket.booking.service.BookingService;
import ticket.booking.service.TrainService;
import ticket.booking.service.UserService;
import ticket.booking.utils.UserServiceUtil;

import java.io.IOException;
import java.util.*;
public class App {

    public static void main(String[] args) throws IOException {

        Scanner sc = new Scanner(System.in);

        UserService userService = new UserService();

        TrainService trainService = new TrainService();

        BookingService bookingService =
                new BookingService(userService, trainService);

        while (true) {

            System.out.println("\n TRAIN BOOKING SYSTEM ");

            System.out.println("1. Register");

            System.out.println("2. Login");

            System.out.println("3. Exit");

            int choice = sc.nextInt();

            switch (choice) {

                case 1 -> {

                    System.out.print("Username : ");

                    String name = sc.next();

                    System.out.print("Password : ");

                    String password = sc.next();

                    User user = new User(

                            name,


                            UserServiceUtil.hashPassword(password),

                            new ArrayList<>(),

                            UUID.randomUUID().toString()

                    );

                    boolean success =
                            userService.register(user);

                    if (success)

                        System.out.println("Registration Successful");

                    else

                        System.out.println("Username Already Exists");

                }

                case 2 -> {

                    System.out.print("Username : ");

                    String username = sc.next();

                    System.out.print("Password : ");

                    String password = sc.next();

                    User loggedUser =
                            userService.login(username, password);

                    if (loggedUser != null) {

                        System.out.println("Login Successful");

                        UserMenu menu =
                                new UserMenu(
                                        bookingService,
                                        trainService
                                );

                        menu.start();

                        userService.logout();

                    } else {

                        System.out.println("Invalid Credentials");

                    }

                }

                case 3 -> {

                    System.out.println("Thank You");

                    System.exit(0);

                }

                default -> System.out.println("Invalid Choice");

            }

        }

    }

}